// 行数据列表/List of rows
const elements = [
    [
        { name: '氢/Hydrogen', symbol: 'H', number: 1, weight: 1.01, type: 'nonmetal' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '氦/Helium', symbol: 'He', number: 2, weight: 4.00, type: 'noblegas' },
    ],
    [
        { name: '锂/Lithium', symbol: 'Li', number: 3, weight: 6.94, type: 'metal' },
        { name: '铍/Beryllium', symbol: 'Be', number: 4, weight: 9.01, type: 'metal' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '硼/Boron', symbol: 'B', number: 5, weight: 10.81, type: 'nonmetal' },
        { name: '碳/Carbon', symbol: 'C', number: 6, weight: 12.01, type: 'nonmetal' },
        { name: '氮/Nitrogen', symbol: 'N', number: 7, weight: 14.01, type: 'nonmetal' },
        { name: '氧/Oxygen', symbol: 'O', number: 8, weight: 16, type: 'nonmetal' },
        { name: '氟/Fluorine', symbol: 'F', number: 9, weight: 19, type: 'nonmetal' },
        { name: '氖/Neon', symbol: 'Ne', number: 10, weight: 20.18, type: 'noblegas' },
    ],
    [
        { name: '钠/Sodium', symbol: 'Na', number: 11, weight: 22.99, type: 'metal' },
        { name: '镁/Magnesium', symbol: 'Mg', number: 12, weight: 24.31, type: 'metal' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '铝/Aluminum', symbol: 'Al', number: 13, weight: 26.98, type: 'metal' },
        { name: '硅/Silicon', symbol: 'Si', number: 14, weight: 28.09, type: 'nonmetal' },
        { name: '磷/Phosphorus', symbol: 'P', number: 15, weight: 30.97, type: 'nonmetal' },
        { name: '硫/Sulfur', symbol: 'S', number: 16, weight: 32.07, type: 'nonmetal' },
        { name: '氯/Chlorine', symbol: 'Cl', number: 17, weight: 35.45, type: 'nonmetal' },
        { name: '氩/Argon', symbol: 'Ar', number: 18, weight: 39.95, type: 'noblegas' },
    ],
    [
        { name: '钾/Potassium', symbol: 'K', number: 19, weight: 39.098, type: 'metal' },
        { name: '钙/Calcium', symbol: 'Ca', number: 20, weight: 40.078, type: 'metal' },
        { name: '钪/Scandium', symbol: 'Sc', number: 21, weight: 44.956, type: 'metal' },
        { name: '钛/Titanium', symbol: 'Ti', number: 22, weight: 47.87, type: 'metal' },
        { name: '钒/Vanadium', symbol: 'V', number: 23, weight: 50.94, type: 'metal' },
        { name: '铬/Chromium', symbol: 'Cr', number: 24, weight: 52, type: 'metal'/*, icon: 'chromium-browser'*/ },
        { name: '锰/Manganese', symbol: 'Mn', number: 25, weight: 54.94, type: 'metal' },
        { name: '铁/Iron', symbol: 'Fe', number: 26, weight: 55.85, type: 'metal' },
        { name: '钴/Cobalt', symbol: 'Co', number: 27, weight: 58.93, type: 'metal' },
        { name: '镍/Nickel', symbol: 'Ni', number: 28, weight: 58.69, type: 'metal' },
        { name: '铜/Copper', symbol: 'Cu', number: 29, weight: 63.55, type: 'metal' },
        { name: '锌/Zinc', symbol: 'Zn', number: 30, weight: 65.38, type: 'metal' },
        { name: '镓/Gallium', symbol: 'Ga', number: 31, weight: 69.72, type: 'metal' },
        { name: '锗/Germanium', symbol: 'Ge', number: 32, weight: 72.63, type: 'metal' },
        { name: '砷/Arsenic', symbol: 'As', number: 33, weight: 74.92, type: 'nonmetal' },
        { name: '硒/Selenium', symbol: 'Se', number: 34, weight: 78.96, type: 'nonmetal' },
        { name: '溴/Bromine', symbol: 'Br', number: 35, weight: 79.904, type: 'nonmetal' },
        { name: '氪/Krypton', symbol: 'Kr', number: 36, weight: 83.8, type: 'noblegas' },
    ],
    [
        { name: '铷/Rubidium', symbol: 'Rb', number: 37, weight: 85.47, type: 'metal' },
        { name: '锶/Strontium', symbol: 'Sr', number: 38, weight: 87.62, type: 'metal' },
        { name: '钇/Yttrium', symbol: 'Y', number: 39, weight: 88.91, type: 'metal' },
        { name: '锆/Zirconium', symbol: 'Zr', number: 40, weight: 91.22, type: 'metal' },
        { name: '铌/Niobium', symbol: 'Nb', number: 41, weight: 92.91, type: 'metal' },
        { name: '钼/Molybdenum', symbol: 'Mo', number: 42, weight: 95.94, type: 'metal' },
        { name: '锝/Technetium', symbol: 'Tc', number: 43, weight: 98, type: 'metal' },
        { name: '钌/Ruthenium', symbol: 'Ru', number: 44, weight: 101.07, type: 'metal' },
        { name: '铑/Rhodium', symbol: 'Rh', number: 45, weight: 102.91, type: 'metal' },
        { name: '钯/Palladium', symbol: 'Pd', number: 46, weight: 106.42, type: 'metal' },
        { name: '银/Silver', symbol: 'Ag', number: 47, weight: 107.87, type: 'metal' },
        { name: '镉/Cadmium', symbol: 'Cd', number: 48, weight: 112.41, type: 'metal' },
        { name: '铟/Indium', symbol: 'In', number: 49, weight: 114.82, type: 'metal' },
        { name: '锡/Tin', symbol: 'Sn', number: 50, weight: 118.71, type: 'metal' },
        { name: '锑/Antimony', symbol: 'Sb', number: 51, weight: 121.76, type: 'metal' },
        { name: '碲/Tellurium', symbol: 'Te', number: 52, weight: 127.6, type: 'nonmetal' },
        { name: '碘/Iodine', symbol: 'I', number: 53, weight: 126.9, type: 'nonmetal' },
        { name: '氙/Xenon', symbol: 'Xe', number: 54, weight: 131.29, type: 'noblegas' },
    ],
    [
        { name: '铯/Cesium', symbol: 'Cs', number: 55, weight: 132.91, type: 'metal' },
        { name: '钡/Barium', symbol: 'Ba', number: 56, weight: 137.33, type: 'metal' },
        { name: '镧/Lanthanum', symbol: 'La', number: 57, weight: 138.91, type: 'lanthanum' },
        { name: '铪/Hafnium', symbol: 'Hf', number: 72, weight: 178.49, type: 'metal' },
        { name: '钽/Tantalum', symbol: 'Ta', number: 73, weight: 180.95, type: 'metal' },
        { name: '钨/Tungsten', symbol: 'W', number: 74, weight: 183.84, type: 'metal' },
        { name: '铼/Rhenium', symbol: 'Re', number: 75, weight: 186.21, type: 'metal' },
        { name: '锇/Osmium', symbol: 'Os', number: 76, weight: 190.23, type: 'metal' },
        { name: '铱/Iridium', symbol: 'Ir', number: 77, weight: 192.22, type: 'metal' },
        { name: '铂/Platinum', symbol: 'Pt', number: 78, weight: 195.09, type: 'metal' },
        { name: '金/Gold', symbol: 'Au', number: 79, weight: 196.97, type: 'metal' },
        { name: '汞/Mercury', symbol: 'Hg', number: 80, weight: 200.59, type: 'metal' },
        { name: '铊/Thallium', symbol: 'Tl', number: 81, weight: 204.38, type: 'metal' },
        { name: '铅/Lead', symbol: 'Pb', number: 82, weight: 207.2, type: 'metal' },
        { name: '铋/Bismuth', symbol: 'Bi', number: 83, weight: 208.98, type: 'metal' },
        { name: '钋/Polonium', symbol: 'Po', number: 84, weight: 209, type: 'metal' },
        { name: '砹/Astatine', symbol: 'At', number: 85, weight: 210, type: 'nonmetal' },
        { name: '氡/Radon', symbol: 'Rn', number: 86, weight: 222, type: 'noblegas' },
    ],
    [
        { name: '钫/Francium', symbol: 'Fr', number: 87, weight: 223, type: 'metal' },
        { name: '镭/Radium', symbol: 'Ra', number: 88, weight: 226, type: 'metal' },
        { name: '锕/Actinium', symbol: 'Ac', number: 89, weight: 227, type: 'actinium' },
        { name: '𬬻/Rutherfordium', symbol: 'Rf', number: 104, weight: 267, type: 'metal' },
        { name: '𬭊/Dubnium', symbol: 'Db', number: 105, weight: 268, type: 'metal' },
        { name: '𬭳/Seaborgium', symbol: 'Sg', number: 106, weight: 271, type: 'metal' },
        { name: '𬭛/Bohrium', symbol: 'Bh', number: 107, weight: 272, type: 'metal' },
        { name: '𬭶/Hassium', symbol: 'Hs', number: 108, weight: 277, type: 'metal' },
        { name: '鿏/Meitnerium', symbol: 'Mt', number: 109, weight: 278, type: 'metal' },
        { name: '𫟼/Darmstadtium', symbol: 'Ds', number: 110, weight: 281, type: 'metal' },
        { name: '𬬭/Roentgenium', symbol: 'Rg', number: 111, weight: 280, type: 'metal' },
        { name: '鿔/Copernicium', symbol: 'Cn', number: 112, weight: 285, type: 'metal' },
        { name: '鿭/Nihonium', symbol: 'Nh', number: 113, weight: 286, type: 'metal' },
        { name: '𫓧/Flerovium', symbol: 'Fl', number: 114, weight: 289, type: 'metal' },
        { name: '镆/Moscovium', symbol: 'Mc', number: 115, weight: 290, type: 'metal' },
        { name: '𫟷/Livermorium', symbol: 'Lv', number: 116, weight: 293, type: 'metal' },
        { name: '鿬/Tennessine', symbol: 'Ts', number: 117, weight: 294, type: 'metal' },
        { name: '鿫/Oganesson', symbol: 'Og', number: 118, weight: 294, type: 'noblegas' },
    ],
]

const series = [
    [
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '铈/Cerium', symbol: 'Ce', number: 58, weight: 140.12, type: 'lanthanum' },
        { name: '镨/Praseodymium', symbol: 'Pr', number: 59, weight: 140.91, type: 'lanthanum' },
        { name: '钕/Neodymium', symbol: 'Nd', number: 60, weight: 144.24, type: 'lanthanum' },
        { name: '钷/Promethium', symbol: 'Pm', number: 61, weight: 145, type: 'lanthanum' },
        { name: '钐/Samarium', symbol: 'Sm', number: 62, weight: 150.36, type: 'lanthanum' },
        { name: '铕/Europium', symbol: 'Eu', number: 63, weight: 151.96, type: 'lanthanum' },
        { name: '钆/Gadolinium', symbol: 'Gd', number: 64, weight: 157.25, type: 'lanthanum' },
        { name: '铽/Terbium', symbol: 'Tb', number: 65, weight: 158.93, type: 'lanthanum' },
        { name: '镝/Dysprosium', symbol: 'Dy', number: 66, weight: 162.5, type: 'lanthanum' },
        { name: '钬/Holmium', symbol: 'Ho', number: 67, weight: 164.93, type: 'lanthanum' },
        { name: '铒/Erbium', symbol: 'Er', number: 68, weight: 167.26, type: 'lanthanum' },
        { name: '铥/Thulium', symbol: 'Tm', number: 69, weight: 168.93, type: 'lanthanum' },
        { name: '镱/Ytterbium', symbol: 'Yb', number: 70, weight: 173.04, type: 'lanthanum' },
        { name: '镥/Lutetium', symbol: 'Lu', number: 71, weight: 174.97, type: 'lanthanum' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
    ],
    [
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '钍/Thorium', symbol: 'Th', number: 90, weight: 232.04, type: 'actinium' },
        { name: '镤/Protactinium', symbol: 'Pa', number: 91, weight: 231.04, type: 'actinium' },
        { name: '铀/Uranium', symbol: 'U', number: 92, weight: 238.03, type: 'actinium' },
        { name: '镎/Neptunium', symbol: 'Np', number: 93, weight: 237, type: 'actinium' },
        { name: '钚/Plutonium', symbol: 'Pu', number: 94, weight: 244, type: 'actinium' },
        { name: '镅/Americium', symbol: 'Am', number: 95, weight: 243, type: 'actinium' },
        { name: '锔/Curium', symbol: 'Cm', number: 96, weight: 247, type: 'actinium' },
        { name: '锫/Berkelium', symbol: 'Bk', number: 97, weight: 247, type: 'actinium' },
        { name: '锎/Californium', symbol: 'Cf', number: 98, weight: 251, type: 'actinium' },
        { name: '锿/Einsteinium', symbol: 'Es', number: 99, weight: 252, type: 'actinium' },
        { name: '镄/Fermium', symbol: 'Fm', number: 100, weight: 257, type: 'actinium' },
        { name: '钔/Mendelevium', symbol: 'Md', number: 101, weight: 258, type: 'actinium' },
        { name: '锘/Nobelium', symbol: 'No', number: 102, weight: 259, type: 'actinium' },
        { name: '铹/Lawrencium', symbol: 'Lr', number: 103, weight: 262, type: 'actinium' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
    ],
];

const niceTypes = {
    'metal': "金属/Metal",
    'nonmetal': "非金属/Nonmetal",
    'noblegas': "稀有气体/Noble gas",
    'lanthanum': "镧系元素/Lanthanum",
    'actinium': "锕系元素/Actinium"
}